"use client";

import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Banknote,
  BarChart3,
  Bell,
  Building2,
  Calendar,
  CalendarCheck,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Clock,
  Columns2,
  Command,
  Copy,
  Crown,
  Download,
  Equal,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  Flame,
  Globe2,
  Grid2x2,
  Hammer,
  Info,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  ListOrdered,
  Lock,
  Magnet,
  Maximize,
  Menu,
  Minus,
  Moon,
  MousePointer,
  Move,
  Newspaper,
  Pencil,
  Percent,
  PieChart,
  Plane,
  Plus,
  RefreshCw,
  Rows2,
  Ruler,
  Search,
  Settings,
  Slash,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Sun,
  Target,
  Trash,
  TrendingDown,
  TrendingUp,
  Type,
  Undo,
  Redo,
  Wallet,
  Wind,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const ICONS = {
  bell: Bell,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  search: Search,
  menu: Menu,
  settings: Settings,
  star: Star,
  crown: Crown,
  command: Command,
  newspaper: Newspaper,
  refresh: RefreshCw,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  swap: ArrowLeftRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  flame: Flame,
  layoutGrid: LayoutGrid,
  layoutDashboard: LayoutDashboard,
  listOrdered: ListOrdered,
  barChart: BarChart3,
  pieChart: PieChart,
  lineChart: LineChart,
  banknote: Banknote,
  wallet: Wallet,
  target: Target,
  sliders: SlidersHorizontal,
  globe: Globe2,
  external: ExternalLink,
  sparkles: Sparkles,
  sun: Sun,
  moon: Moon,
  plus: Plus,
  close: X,
  info: Info,
  alert: AlertTriangle,
  building: Building2,
  activity: Activity,
  lock: Lock,
  clock: Clock,
  check: Check,
  pencil: Pencil,
  maximize: Maximize,
  chevronsUpDown: ChevronsUpDown,
  plane: Plane,
  download: Download,
  copy: Copy,
  grid2x2: Grid2x2,
  columns2: Columns2,
  rows2: Rows2,
  mousePointer: MousePointer,
  move: Move,
  minus: Minus,
  slash: Slash,
  square: Square,
  equal: Equal,
  percent: Percent,
  ruler: Ruler,
  type: Type,
  eraser: Eraser,
  hammer: Hammer,
  wind: Wind,
  magnet: Magnet,
  eye: Eye,
  eyeOff: EyeOff,
  undo: Undo,
  redo: Redo,
  trash: Trash,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

interface AppIconProps {
  name: IconName;
  size?: number;
  className?: string;
  strokeWidth?: number;
  color?: string;
}

export function AppIcon({ name, size = 16, className, strokeWidth = 1.8, color }: AppIconProps) {
  const Cmp = ICONS[name];
  return <Cmp size={size} className={className} strokeWidth={strokeWidth} color={color} />;
}
