/* AUTO-GENERATED by tokens/build/generate.mjs — DO NOT EDIT */
/* 기존 ds/tokens 배럴과 API 호환 — var() 참조는 v3 변수명(--jd-*)을 가리킨다 (02-tokens §4.3).
   themes/brands 함수류(applyTheme 등)와 animationClass는 생성 대상이 아니라 런타임 코드 (§4.4·§4.5). */

export const colors = {
  primary: {
    DEFAULT: "var(--jd-color-primary)",
    hover: "var(--jd-color-primary-hover)",
    light: "var(--jd-color-primary-light)",
    glow: "var(--jd-color-primary-glow)",
  },
  accent: {
    DEFAULT: "var(--jd-color-accent)",
    light: "var(--jd-color-accent-light)",
  },
  success: {
    DEFAULT: "var(--jd-color-success)",
    light: "var(--jd-color-success-light)",
  },
  warning: {
    DEFAULT: "var(--jd-color-warning)",
    light: "var(--jd-color-warning-light)",
  },
  danger: {
    DEFAULT: "var(--jd-color-danger)",
    hover: "var(--jd-color-danger-hover)",
    light: "var(--jd-color-danger-light)",
  },
  info: {
    DEFAULT: "var(--jd-color-info)",
    light: "var(--jd-color-info-light)",
  },
  neutral: {
    background: "var(--jd-color-background)",
    foreground: "var(--jd-color-foreground)",
    card: "var(--jd-color-card)",
    cardHover: "var(--jd-color-card-hover)",
    border: "var(--jd-color-border)",
    borderLight: "var(--jd-color-border-light)",
    muted: "var(--jd-color-muted)",
    mutedLight: "var(--jd-color-muted-light)",
  },
  sidebar: {
    bg: "var(--jd-color-sidebar-bg)",
    hover: "var(--jd-color-sidebar-hover)",
    text: "var(--jd-color-sidebar-text)",
    active: "var(--jd-color-sidebar-active)",
  },
} as const;

export const priorityColors = {
  0: {
    label: "긴급",
    bg: "#fef2f2",
    text: "#dc2626",
    border: "#fca5a5",
  },
  1: {
    label: "높음",
    bg: "#fff7ed",
    text: "#ea580c",
    border: "#fdba74",
  },
  2: {
    label: "보통",
    bg: "#fefce8",
    text: "#ca8a04",
    border: "#fde047",
  },
  3: {
    label: "낮음",
    bg: "#eff6ff",
    text: "#2563eb",
    border: "#93c5fd",
  },
} as const;

export const statusColors = {
  todo: {
    bg: "#f3f4f6",
    text: "#6b7280",
  },
  progress: {
    bg: "#dbeafe",
    text: "#2563eb",
  },
  review: {
    bg: "#fef3c7",
    text: "#d97706",
  },
  done: {
    bg: "#d1fae5",
    text: "#059669",
  },
  hold: {
    bg: "#fee2e2",
    text: "#dc2626",
  },
} as const;

export const spacing = {
  0: "0",
  1: "0.25rem",
  2: "0.5rem",
  3: "0.75rem",
  4: "1rem",
  5: "1.25rem",
  6: "1.5rem",
  8: "2rem",
  10: "2.5rem",
  12: "3rem",
  16: "4rem",
  20: "5rem",
  24: "6rem",
  px: "1px",
  0.5: "0.125rem",
  1.5: "0.375rem",
  2.5: "0.625rem",
  3.5: "0.875rem",
} as const;

export const fontSize = {
  xs: "0.75rem",
  sm: "0.8125rem",
  md: "0.875rem",
  lg: "1rem",
  xl: "1.125rem",
  "2xl": "1.25rem",
  "3xl": "1.5rem",
  "4xl": "1.875rem",
  "5xl": "2.25rem",
} as const;

export const fontWeight = {
  normal: "400",
  medium: "500",
  semibold: "600",
  bold: "700",
} as const;

export const lineHeight = {
  none: "1",
  tight: "1.25",
  snug: "1.375",
  normal: "1.5",
  relaxed: "1.625",
  loose: "2",
} as const;

export const letterSpacing = {
  tighter: "-0.05em",
  tight: "-0.025em",
  normal: "0em",
  wide: "0.025em",
} as const;

export const fontFamily = {
  sans: "'Pretendard', 'Inter', -apple-system, 'Segoe UI', sans-serif",
  serif: "'Noto Serif KR', 'Source Serif Pro', Georgia, serif",
  mono: "'JetBrains Mono', 'Geist Mono', ui-monospace, monospace",
} as const;

export const shadows = {
  none: "none",
  xs: "0 1px 2px rgba(0,0,0,0.04)",
  sm: "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
  md: "0 4px 6px -1px rgba(0,0,0,0.07), 0 2px 4px -2px rgba(0,0,0,0.05)",
  lg: "0 10px 15px -3px rgba(0,0,0,0.08), 0 4px 6px -4px rgba(0,0,0,0.04)",
  xl: "0 20px 25px -5px rgba(0,0,0,0.08), 0 8px 10px -6px rgba(0,0,0,0.04)",
  "2xl": "0 25px 50px -12px rgba(0,0,0,0.15)",
  glow: "0 0 0 3px var(--jd-color-primary-glow)",
  danger: "0 0 0 3px rgba(220,63,63,0.15)",
} as const;

export const radius = {
  none: "0",
  sm: "0.25rem",
  md: "0.375rem",
  lg: "0.5rem",
  xl: "0.75rem",
  "2xl": "1rem",
  full: "9999px",
} as const;

export const duration = {
  instant: "0ms",
  fast: "100ms",
  normal: "200ms",
  slow: "300ms",
  slower: "500ms",
} as const;

export const easing = {
  default: "cubic-bezier(0.16, 1, 0.3, 1)",
  linear: "linear",
  easeIn: "cubic-bezier(0.4, 0, 1, 1)",
  easeOut: "cubic-bezier(0, 0, 0.2, 1)",
  easeInOut: "cubic-bezier(0.4, 0, 0.2, 1)",
  spring: "cubic-bezier(0.16, 1, 0.3, 1)",
} as const;

export const zIndex = {
  hide: -1,
  base: 0,
  dropdown: 10,
  sticky: 20,
  header: 30,
  overlay: 40,
  modal: 50,
  popover: 60,
  toast: 70,
  tooltip: 80,
  max: 9999,
} as const;

export const opacity = {
  0: "0",
  5: "0.05",
  10: "0.1",
  15: "0.15",
  20: "0.2",
  25: "0.25",
  30: "0.3",
  40: "0.4",
  50: "0.5",
  60: "0.6",
  70: "0.7",
  75: "0.75",
  80: "0.8",
  90: "0.9",
  95: "0.95",
  100: "1",
} as const;
export type OpacityScale = keyof typeof opacity;

export const borderWidth = {
  none: "0px",
  thin: "1px",
  medium: "2px",
  thick: "3px",
  heavy: "4px",
} as const;
export type BorderWidthScale = keyof typeof borderWidth;

export const breakpoints = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  "2xl": 1536,
} as const;
export type Breakpoint = keyof typeof breakpoints;

export const mediaQueries: Record<Breakpoint, string> = {
  sm: "(min-width: 640px)",
  md: "(min-width: 768px)",
  lg: "(min-width: 1024px)",
  xl: "(min-width: 1280px)",
  "2xl": "(min-width: 1536px)",
};

export const gradients = {
  primary: "linear-gradient(135deg, var(--jd-color-primary) 0%, var(--jd-color-primary-hover) 100%)",
  primarySoft: "linear-gradient(135deg, var(--primary-soft) 0%, var(--jd-color-primary-glow) 100%)",
  success: "linear-gradient(135deg, #22c55e 0%, #16a34a 100%)",
  warning: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
  danger: "linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)",
  info: "linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)",
  surfaceTop: "linear-gradient(180deg, var(--surface) 0%, transparent 100%)",
  surfaceBottom: "linear-gradient(0deg, var(--surface) 0%, transparent 100%)",
  sunset: "linear-gradient(135deg, #ff7e5f 0%, #feb47b 100%)",
  ocean: "linear-gradient(135deg, #2193b0 0%, #6dd5ed 100%)",
  aurora: "linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)",
  midnight: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
  cyber: "linear-gradient(135deg, #ff00cc 0%, #333399 100%)",
  forest: "linear-gradient(135deg, #134e5e 0%, #71b280 100%)",
  flame: "linear-gradient(135deg, #ff416c 0%, #ff4b2b 100%)",
  candy: "linear-gradient(135deg, #ee9ca7 0%, #ffdde1 100%)",
  shimmer: "linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.4) 50%, transparent 100%)",
} as const;
export type GradientPreset = keyof typeof gradients;
