export interface ComponentPreview {
  icon: string; // emoji
  description: string; // 핵심 기능 한줄 설명 (Korean)
  color: string; // Tailwind bg color for the card
}

export const componentPreviews: Record<string, ComponentPreview> = {
  // Foundation
  개요: { icon: "🏠", description: "디자인 시스템 전체 개요", color: "bg-violet-500/20" },
  Colors: { icon: "🎨", description: "CSS 변수 기반 시맨틱 컬러", color: "bg-violet-500/20" },
  Typography: { icon: "✏️", description: "글꼴 크기, 두께, 행간", color: "bg-violet-500/20" },
  Spacing: { icon: "📏", description: "4px 단위 간격 체계", color: "bg-violet-500/20" },
  Shadows: { icon: "🌑", description: "6단계 엘리베이션 그림자", color: "bg-violet-500/20" },
  Animations: { icon: "✨", description: "스프링 기반 애니메이션", color: "bg-violet-500/20" },

  // Primitives
  Button: { icon: "🔘", description: "6가지 변형, 4가지 크기", color: "bg-blue-500/20" },
  Input: { icon: "📝", description: "텍스트 입력 필드", color: "bg-blue-500/20" },
  Textarea: { icon: "📄", description: "여러 줄 텍스트 입력", color: "bg-blue-500/20" },
  Badge: { icon: "🏷", description: "상태 표시 배지", color: "bg-blue-500/20" },
  Avatar: { icon: "👤", description: "프로필 이미지/이니셜", color: "bg-blue-500/20" },
  Spinner: { icon: "⟳", description: "로딩 인디케이터", color: "bg-blue-500/20" },
  Divider: { icon: "─", description: "구분선", color: "bg-blue-500/20" },
  Toggle: { icon: "🔄", description: "온/오프 토글", color: "bg-blue-500/20" },
  Checkbox: { icon: "☑", description: "체크박스 선택", color: "bg-blue-500/20" },
  Radio: { icon: "⊙", description: "단일 선택 라디오", color: "bg-blue-500/20" },
  Tag: { icon: "🔖", description: "태그/칩 표시", color: "bg-blue-500/20" },
  IconButton: { icon: "⊕", description: "아이콘 전용 버튼", color: "bg-blue-500/20" },
  Kbd: { icon: "⌨", description: "키보드 단축키 표시", color: "bg-blue-500/20" },
  Slider: { icon: "━", description: "범위 슬라이더", color: "bg-blue-500/20" },
  NumberInput: { icon: "#", description: "숫자 증감 입력", color: "bg-blue-500/20" },
  FileUpload: { icon: "📎", description: "파일 업로드 영역", color: "bg-blue-500/20" },
  CopyButton: { icon: "📋", description: "클립보드 복사 버튼", color: "bg-blue-500/20" },
  StatusDot: { icon: "●", description: "상태 표시 점", color: "bg-blue-500/20" },
  Switch: { icon: "⏻", description: "iOS 스타일 스위치", color: "bg-blue-500/20" },
  AspectRatio: { icon: "▣", description: "종횡비 유지 컨테이너", color: "bg-blue-500/20" },
  ScrollArea: { icon: "↕", description: "커스텀 스크롤바", color: "bg-blue-500/20" },
  StarRating: { icon: "⭐", description: "별점 입력/표시", color: "bg-blue-500/20" },
  BackTop: { icon: "⬆", description: "맨 위로 스크롤", color: "bg-blue-500/20" },
  BatteryIndicator: { icon: "🔋", description: "배터리 레벨 표시", color: "bg-blue-500/20" },
  SeverityBadge: { icon: "⚠", description: "심각도 상태 배지", color: "bg-blue-500/20" },

  // Composites
  Select: { icon: "▾", description: "드롭다운 선택", color: "bg-emerald-500/20" },
  MultiSelect: { icon: "☰", description: "다중 선택 드롭다운", color: "bg-emerald-500/20" },
  Modal: { icon: "⬜", description: "대화 상자 오버레이", color: "bg-emerald-500/20" },
  Toast: { icon: "🔔", description: "알림 메시지 팝업", color: "bg-emerald-500/20" },
  Dropdown: { icon: "▼", description: "메뉴 드롭다운", color: "bg-emerald-500/20" },
  Tabs: { icon: "⊞", description: "탭 네비게이션", color: "bg-emerald-500/20" },
  Accordion: { icon: "▽", description: "접기/펼치기 패널", color: "bg-emerald-500/20" },
  Breadcrumb: { icon: "/", description: "경로 네비게이션", color: "bg-emerald-500/20" },
  Progress: { icon: "▓", description: "진행률 표시", color: "bg-emerald-500/20" },
  Tooltip: { icon: "💬", description: "호버 도움말 팝업", color: "bg-emerald-500/20" },
  Card: { icon: "🃏", description: "카드 컨테이너", color: "bg-emerald-500/20" },
  Alert: { icon: "⚠", description: "알림/경고 메시지", color: "bg-emerald-500/20" },
  EmptyState: { icon: "∅", description: "데이터 없음 표시", color: "bg-emerald-500/20" },
  Skeleton: { icon: "▒", description: "로딩 뼈대 UI", color: "bg-emerald-500/20" },
  Pagination: { icon: "«»", description: "페이지 네비게이션", color: "bg-emerald-500/20" },
  DateInput: { icon: "📅", description: "날짜 입력 필드", color: "bg-emerald-500/20" },
  Drawer: { icon: "◫", description: "슬라이드 패널", color: "bg-emerald-500/20" },
  ConfirmDialog: { icon: "❓", description: "확인/취소 대화상자", color: "bg-emerald-500/20" },
  Combobox: { icon: "🔎", description: "검색+선택 콤보", color: "bg-emerald-500/20" },
  StatCard: { icon: "📈", description: "통계 수치 카드", color: "bg-emerald-500/20" },
  Timeline: { icon: "⏱", description: "시간순 이벤트 표시", color: "bg-emerald-500/20" },
  ButtonGroup: { icon: "▣", description: "버튼 그룹 묶음", color: "bg-emerald-500/20" },
  AvatarStack: { icon: "👥", description: "아바타 겹침 표시", color: "bg-emerald-500/20" },
  Collapsible: { icon: "⤵", description: "접기/펼치기 영역", color: "bg-emerald-500/20" },
  HoverCard: { icon: "🪧", description: "호버 정보 카드", color: "bg-emerald-500/20" },
  ContextMenu: { icon: "📋", description: "우클릭 컨텍스트 메뉴", color: "bg-emerald-500/20" },
  AlertDialog: { icon: "🚨", description: "경고 대화상자", color: "bg-emerald-500/20" },
  Sheet: { icon: "📑", description: "바텀/사이드 시트", color: "bg-emerald-500/20" },
  NavigationMenu: { icon: "🧭", description: "네비게이션 메뉴", color: "bg-emerald-500/20" },
  Menubar: { icon: "☰", description: "메뉴바 모음", color: "bg-emerald-500/20" },
  Table: { icon: "📊", description: "데이터 테이블", color: "bg-emerald-500/20" },
  Carousel: { icon: "🎠", description: "슬라이드 캐러셀", color: "bg-emerald-500/20" },
  Resizable: { icon: "↔", description: "크기 조절 패널", color: "bg-emerald-500/20" },
  TreeView: { icon: "🌲", description: "트리 구조 표시", color: "bg-emerald-500/20" },
  Stepper: { icon: "1→2", description: "단계별 진행 표시", color: "bg-emerald-500/20" },
  Transfer: { icon: "⇄", description: "항목 이동 전송", color: "bg-emerald-500/20" },
  Descriptions: { icon: "📃", description: "설명 키-값 목록", color: "bg-emerald-500/20" },
  SegmentedControl: { icon: "▤", description: "세그먼트 분류 컨트롤", color: "bg-emerald-500/20" },
  ColorPicker: { icon: "🎨", description: "색상 선택기", color: "bg-emerald-500/20" },
  TimePicker: { icon: "🕐", description: "시간 선택기", color: "bg-emerald-500/20" },
  DateRangePicker: { icon: "📆", description: "날짜 범위 선택", color: "bg-emerald-500/20" },
  Mention: { icon: "@", description: "멘션/태그 입력", color: "bg-emerald-500/20" },
  AutoComplete: { icon: "🔍", description: "자동완성 입력", color: "bg-emerald-500/20" },
  Result: { icon: "✅", description: "결과 페이지 표시", color: "bg-emerald-500/20" },
  Watermark: { icon: "💧", description: "워터마크 오버레이", color: "bg-emerald-500/20" },
  ScrollSpy: { icon: "👁", description: "스크롤 위치 감지", color: "bg-emerald-500/20" },
  Spotlight: { icon: "🔦", description: "요소 강조 스포트라이트", color: "bg-emerald-500/20" },
  DateRangeFilter: { icon: "📅", description: "날짜 범위 필터", color: "bg-emerald-500/20" },
  ComparisonGrid: { icon: "⚖", description: "비교 그리드 카드", color: "bg-emerald-500/20" },
  FilterButtonGroup: { icon: "🔽", description: "필터 버튼 그룹", color: "bg-emerald-500/20" },
  KeyValueGrid: { icon: "🗂", description: "키-값 메타데이터 그리드", color: "bg-emerald-500/20" },
  DetailPanel: { icon: "📐", description: "상세 사이드 패널", color: "bg-emerald-500/20" },
  FloatingActionButton: { icon: "⊕", description: "플로팅 액션 버튼", color: "bg-emerald-500/20" },
  CollectionView: { icon: "🖼", description: "갤러리 뷰 컬렉션", color: "bg-emerald-500/20" },

  // Patterns
  DataTable: { icon: "📊", description: "정렬/필터 데이터 테이블", color: "bg-amber-500/20" },
  FilterBar: { icon: "🔍", description: "검색/필터 바", color: "bg-amber-500/20" },
  CommandPalette: { icon: "⌘", description: "명령어 팔레트", color: "bg-amber-500/20" },
  Sidebar: { icon: "◧", description: "사이드바 레이아웃", color: "bg-amber-500/20" },
  Calendar: { icon: "📅", description: "달력 캘린더", color: "bg-amber-500/20" },
  Kanban: { icon: "📋", description: "칸반 보드", color: "bg-amber-500/20" },
  StatsGrid: { icon: "📈", description: "통계 그리드 대시보드", color: "bg-amber-500/20" },
  ActionBar: { icon: "⚡", description: "액션 바 툴바", color: "bg-amber-500/20" },
  FormBuilder: { icon: "📝", description: "동적 폼 빌더", color: "bg-amber-500/20" },
  InfiniteList: { icon: "∞", description: "무한 스크롤 목록", color: "bg-amber-500/20" },
  VirtualList: { icon: "📜", description: "가상화 리스트", color: "bg-amber-500/20" },
  ChartCard: { icon: "📉", description: "차트 카드 위젯", color: "bg-amber-500/20" },
  NotificationCenter: { icon: "🔔", description: "알림 센터", color: "bg-amber-500/20" },
  SortableList: { icon: "↕", description: "드래그 정렬 목록", color: "bg-amber-500/20" },
  RichTextEditor: { icon: "✍", description: "리치 텍스트 편집기", color: "bg-amber-500/20" },
  Tour: { icon: "🗺", description: "온보딩 가이드 투어", color: "bg-amber-500/20" },
  FlowDiagram: { icon: "🔀", description: "노드 플로우 다이어그램", color: "bg-amber-500/20" },

  // Security
  PasswordInput: { icon: "🔒", description: "비밀번호 입력 필드", color: "bg-red-500/20" },
  PinInput: { icon: "🔢", description: "PIN/인증번호 입력", color: "bg-red-500/20" },
  SecurityBadge: { icon: "🛡", description: "보안 등급 배지", color: "bg-red-500/20" },
  TrustIndicator: { icon: "✓", description: "신뢰도 지표 표시", color: "bg-red-500/20" },
  SecurityChecklist: { icon: "☑", description: "보안 체크리스트", color: "bg-red-500/20" },
  LoginForm: { icon: "🔑", description: "로그인 폼", color: "bg-red-500/20" },

  // Advanced
  "Dependency Graph": { icon: "🕸", description: "컴포넌트 의존성 그래프", color: "bg-rose-500/20" },
  "Token Export": { icon: "📤", description: "디자인 토큰 내보내기", color: "bg-rose-500/20" },
  "AI Prompt Generator": { icon: "🤖", description: "AI 프롬프트 생성기", color: "bg-rose-500/20" },
  Changelog: { icon: "📝", description: "변경 이력 로그", color: "bg-rose-500/20" },

  // Lab
  실험실: { icon: "🧪", description: "실험적 컴포넌트", color: "bg-cyan-500/20" },
};
