/* AUTO-GENERATED by tokens/build/generate.mjs — DO NOT EDIT */
/**
 * 웹 런타임이 **숫자로** 필요한 토큰. CSS 변수로 풀 수 있는 것은 여기 없다 —
 * `@media` 조건과 JS 폭 비교만 var()를 쓸 수 없기 때문이다.
 */

/** min-width 미디어 조건 기준점 (px) */
export const BREAKPOINTS = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  "2xl": 1536,
} as const;
export type BreakpointName = keyof typeof BREAKPOINTS;

/** 본문 폭 상한 (px). "full"은 상한 없음이라 여기 없다 */
export const CONTAINER_SIZES = {
  xs: 512,
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  "2xl": 1536,
} as const;
export type ContainerSizeName = keyof typeof CONTAINER_SIZES | "full";
