#!/usr/bin/env node
//
// Generates `.ai/MAP.md` — a single flat inventory of every file an AI agent
// is likely to touch. Reading this one file replaces dozens of glob/grep calls.
//
// Run after structural changes:  npm run map

import { readdir, writeFile, mkdir, stat } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(repoRoot, ".ai");
const outFile = path.join(outDir, "MAP.md");

const SECTIONS = [
  {
    title: "Requirements (read FIRST for any feature work)",
    root: "requirements",
    accept: (rel) => rel.endsWith(".md"),
  },
  {
    title: "Primitives  (`ds/primitives/`)",
    root: "ds/primitives",
    accept: (rel) => rel.endsWith(".tsx") && !rel.includes("__tests__"),
  },
  {
    title: "Composites  (`ds/composites/`)",
    root: "ds/composites",
    accept: (rel) => rel.endsWith(".tsx") && !rel.includes("__tests__"),
  },
  {
    title: "Patterns  (`ds/patterns/`)",
    root: "ds/patterns",
    accept: (rel) => rel.endsWith(".tsx") && !rel.includes("__tests__"),
  },
  {
    title: "Layout  (`ds/layout/`)",
    root: "ds/layout",
    accept: (rel) => /\.(tsx?|ts)$/.test(rel) && !rel.endsWith("index.ts"),
  },
  {
    title: "Hooks  (`ds/hooks/`)",
    root: "ds/hooks",
    accept: (rel) => rel.endsWith(".ts") && !rel.endsWith("index.ts"),
  },
  {
    title: "Tokens  (`ds/tokens/`)",
    root: "ds/tokens",
    accept: (rel) => rel.endsWith(".ts") && !rel.endsWith("index.ts"),
  },
  {
    title: "Providers / Core / Utils / Auth",
    root: "ds",
    accept: (rel) =>
      /^(providers|core|utils|auth)\//.test(rel) &&
      /\.(tsx?|ts)$/.test(rel) &&
      !rel.endsWith("index.ts"),
  },
  {
    title: "Showcase routes  (`app/**/page.tsx`)",
    root: "app",
    accept: (rel) => rel.endsWith("/page.tsx"),
  },
  {
    title: "Showcase data  (`app/design-system/_data/`)",
    root: "app/design-system/_data",
    accept: (rel) => /\.(tsx?|ts)$/.test(rel),
  },
  {
    title: "Tests  (`ds/__tests__/`)",
    root: "ds/__tests__",
    accept: (rel) => rel.endsWith(".test.tsx") || rel.endsWith(".test.ts"),
  },
];

const SKIP_DIRS = new Set([
  ".git",
  ".next",
  "node_modules",
  "dist",
  "coverage",
  ".turbo",
]);

async function walk(absRoot) {
  const out = [];
  async function recur(abs) {
    let entries;
    try {
      entries = await readdir(abs, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (SKIP_DIRS.has(e.name)) continue;
      const next = path.join(abs, e.name);
      if (e.isDirectory()) {
        await recur(next);
      } else if (e.isFile()) {
        out.push(path.relative(absRoot, next));
      }
    }
  }
  await recur(absRoot);
  return out;
}

async function dirExists(p) {
  try {
    const s = await stat(p);
    return s.isDirectory();
  } catch {
    return false;
  }
}

const lines = [];
lines.push("# Project Map");
lines.push("");
lines.push(
  "_Auto-generated by `npm run map`. Do not edit by hand — your edits will be lost._",
);
lines.push("");
lines.push(
  "This file is the **single fastest way** for an AI agent to learn the layout of",
);
lines.push(
  "this repo. Read it once instead of running many `glob`/`grep` calls. After any",
);
lines.push("structural change (new component, deleted file, renamed dir), run:");
lines.push("");
lines.push("```bash");
lines.push("npm run map");
lines.push("```");
lines.push("");
lines.push(`Generated: ${new Date().toISOString()}`);
lines.push("");
lines.push("---");
lines.push("");

let totalFiles = 0;

for (const section of SECTIONS) {
  const absRoot = path.join(repoRoot, section.root);
  if (!(await dirExists(absRoot))) continue;

  const files = (await walk(absRoot))
    .filter((rel) => section.accept(rel))
    .sort((a, b) => a.localeCompare(b));

  if (files.length === 0) continue;

  lines.push(`## ${section.title}`);
  lines.push("");
  lines.push(`_${files.length} file${files.length === 1 ? "" : "s"}_`);
  lines.push("");
  for (const rel of files) {
    lines.push(`- \`${section.root}/${rel}\``);
  }
  lines.push("");
  totalFiles += files.length;
}

lines.push("---");
lines.push("");
lines.push(`**Total indexed files:** ${totalFiles}`);
lines.push("");

await mkdir(outDir, { recursive: true });
await writeFile(outFile, lines.join("\n"), "utf8");

console.log(`[build-map] wrote ${path.relative(repoRoot, outFile)} — ${totalFiles} files`);
