#!/usr/bin/env node
//
// Generates `.ai/MAP.md` — a single flat inventory of every file an AI agent
// is likely to touch. Reading this one file replaces dozens of glob/grep calls.
//
// Run after structural changes:  npm run map

import { readdir, writeFile, mkdir, stat, readFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(repoRoot, ".ai");
const outFile = path.join(outDir, "MAP.md");
const cacheFile = path.join(outDir, ".map-cache.json");

const SECTIONS = [
  {
    title: "Requirements (read FIRST for any feature work)",
    root: "requirements",
    accept: (rel) => rel.endsWith(".md"),
  },
  {
    title: "Primitives  (`ds/primitives/`)",
    root: "ds/primitives",
    accept: (rel) => rel.endsWith(".tsx") && !rel.includes("__tests__"),
  },
  {
    title: "Composites  (`ds/composites/`)",
    root: "ds/composites",
    accept: (rel) => rel.endsWith(".tsx") && !rel.includes("__tests__"),
  },
  {
    title: "Patterns  (`ds/patterns/`)",
    root: "ds/patterns",
    accept: (rel) => rel.endsWith(".tsx") && !rel.includes("__tests__"),
  },
  {
    title: "Layout  (`ds/layout/`)",
    root: "ds/layout",
    accept: (rel) => /\.(tsx?|ts)$/.test(rel) && !rel.endsWith("index.ts"),
  },
  {
    title: "Hooks  (`ds/hooks/`)",
    root: "ds/hooks",
    accept: (rel) => rel.endsWith(".ts") && !rel.endsWith("index.ts"),
  },
  {
    title: "Tokens  (`ds/tokens/`)",
    root: "ds/tokens",
    accept: (rel) => rel.endsWith(".ts") && !rel.endsWith("index.ts"),
  },
  {
    title: "Providers / Core / Utils / Auth",
    root: "ds",
    accept: (rel) =>
      /^(providers|core|utils|auth)\//.test(rel) &&
      /\.(tsx?|ts)$/.test(rel) &&
      !rel.endsWith("index.ts"),
  },
  {
    title: "Showcase routes  (`app/**/page.tsx`)",
    root: "app",
    accept: (rel) => rel.endsWith("/page.tsx"),
  },
  {
    title: "Showcase data  (`app/design-system/_data/`)",
    root: "app/design-system/_data",
    accept: (rel) => /\.(tsx?|ts)$/.test(rel),
  },
  {
    title: "Tests  (`ds/__tests__/`)",
    root: "ds/__tests__",
    accept: (rel) => rel.endsWith(".test.tsx") || rel.endsWith(".test.ts"),
  },
];

const SKIP_DIRS = new Set([
  ".git",
  ".next",
  "node_modules",
  "dist",
  "coverage",
  ".turbo",
]);

// Walks a directory tree once, returning relative paths and the latest mtime
// observed (so callers can skip re-walking when nothing changed).
async function walk(absRoot) {
  const out = [];
  let latestMtime = 0;
  async function recur(abs) {
    let entries;
    try {
      entries = await readdir(abs, { withFileTypes: true });
    } catch {
      return;
    }
    const subdirs = [];
    for (const e of entries) {
      if (SKIP_DIRS.has(e.name)) continue;
      const next = path.join(abs, e.name);
      if (e.isDirectory()) {
        subdirs.push(next);
      } else if (e.isFile()) {
        out.push(path.relative(absRoot, next));
      }
    }
    // Stat the directory itself — directory mtime updates whenever a child is
    // added/removed/renamed, which is the cheapest invalidation signal.
    try {
      const s = await stat(abs);
      if (s.mtimeMs > latestMtime) latestMtime = s.mtimeMs;
    } catch {}
    await Promise.all(subdirs.map(recur));
  }
  await recur(absRoot);
  return { files: out, latestMtime };
}

async function dirExists(p) {
  try {
    const s = await stat(p);
    return s.isDirectory();
  } catch {
    return false;
  }
}

const lines = [];
lines.push("# Project Map");
lines.push("");
lines.push(
  "_Auto-generated by `npm run map`. Do not edit by hand — your edits will be lost._",
);
lines.push("");
lines.push(
  "This file is the **single fastest way** for an AI agent to learn the layout of",
);
lines.push(
  "this repo. Read it once instead of running many `glob`/`grep` calls. After any",
);
lines.push("structural change (new component, deleted file, renamed dir), run:");
lines.push("");
lines.push("```bash");
lines.push("npm run map");
lines.push("```");
lines.push("");
lines.push(`Generated: ${new Date().toISOString()}`);
lines.push("");
lines.push("---");
lines.push("");

let totalFiles = 0;

// Walk each unique root in parallel and reuse the result across sections that
// share the same root (e.g. requirements/, app/, ds/__tests__/). This replaces
// the old per-section sequential walk.
const uniqueRoots = [...new Set(SECTIONS.map((s) => s.root))];
const walkResults = new Map();
const rootSignatures = {};
await Promise.all(
  uniqueRoots.map(async (root) => {
    const absRoot = path.join(repoRoot, root);
    if (!(await dirExists(absRoot))) return;
    const result = await walk(absRoot);
    walkResults.set(root, result);
    rootSignatures[root] = {
      mtimeMs: result.latestMtime,
      fileCount: result.files.length,
    };
  }),
);

// Mtime-based fast path: if every walked root has the same signature as the
// last successful run, the input set is unchanged and we can skip re-emitting.
let cache;
try {
  cache = JSON.parse(await readFile(cacheFile, "utf8"));
} catch {
  cache = null;
}
const sigEqual =
  cache &&
  Object.keys(rootSignatures).length === Object.keys(cache.signatures || {}).length &&
  Object.entries(rootSignatures).every(([root, sig]) => {
    const prev = cache.signatures?.[root];
    return prev && prev.mtimeMs === sig.mtimeMs && prev.fileCount === sig.fileCount;
  });
if (sigEqual) {
  console.log(
    `[build-map] up-to-date — ${cache.totalFiles} files (${path.relative(repoRoot, outFile)})`,
  );
  process.exit(0);
}

for (const section of SECTIONS) {
  const result = walkResults.get(section.root);
  if (!result) continue;

  const files = result.files
    .filter((rel) => section.accept(rel))
    .sort((a, b) => a.localeCompare(b));

  if (files.length === 0) continue;

  lines.push(`## ${section.title}`);
  lines.push("");
  lines.push(`_${files.length} file${files.length === 1 ? "" : "s"}_`);
  lines.push("");
  for (const rel of files) {
    lines.push(`- \`${section.root}/${rel}\``);
  }
  lines.push("");
  totalFiles += files.length;
}

lines.push("---");
lines.push("");
lines.push(`**Total indexed files:** ${totalFiles}`);
lines.push("");

await mkdir(outDir, { recursive: true });
await Promise.all([
  writeFile(outFile, lines.join("\n"), "utf8"),
  writeFile(
    cacheFile,
    JSON.stringify({ signatures: rootSignatures, totalFiles }),
    "utf8",
  ),
]);

console.log(`[build-map] wrote ${path.relative(repoRoot, outFile)} — ${totalFiles} files`);
