#!/usr/bin/env node
// JunDS Showroom 카탈로그 생성기 — 의존성 0.
// docs-spec/registry/ledger.json(원장 445행)을 읽어 ShowroomCatalog.swift를 방출한다.
// 손으로 목록을 관리하지 않는다 — 원장이 유일한 소스다.
//
// 사용: node demo/tools/gen-catalog.mjs   (레포 루트 기준 상대 경로 자동 해석)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const ledgerPath = join(root, "docs-spec", "registry", "ledger.json");
const outPath = join(root, "demo", "JunDSDemo.swiftpm", "Generated", "ShowroomCatalog.swift");

const ledger = JSON.parse(readFileSync(ledgerPath, "utf8"));
const rows = ledger.rows;
if (!Array.isArray(rows) || rows.length === 0) {
  console.error("ledger rows가 비었다 — 경로/스키마 확인");
  process.exit(1);
}

// 카테고리 순서는 07-rollout 티어 순서를 따른다.
const CATEGORIES = ["core", "layout", "primitives", "hooks", "composites", "patterns", "finance"];
const byCategory = new Map(CATEGORIES.map((c) => [c, []]));
for (const r of rows) {
  if (!byCategory.has(r.category)) {
    console.error(`알 수 없는 카테고리: ${r.category} (${r.id})`);
    process.exit(1);
  }
  byCategory.get(r.category).push(r);
}

// Swift 문자열 리터럴 이스케이프 (한글은 UTF-8 원문 유지)
const esc = (s) =>
  '"' +
  String(s ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "")
    .replace(/\t/g, "\\t") +
  '"';

const entry = (r) =>
  `        CatalogEntry(id: ${esc(r.id)}, category: ${esc(r.category)}, tier: ${esc(r.tier)}, web: ${esc(
    r.web
  )}, ios: ${esc(r.ios)}, docs: ${esc(r.docs)}, tests: ${esc(r.tests)}, bench: ${esc(r.bench)}, note: ${esc(
    r.notes ?? ""
  )}),`;

let swift = `// AUTO-GENERATED by demo/tools/gen-catalog.mjs — DO NOT EDIT.
// Source: docs-spec/registry/ledger.json (${rows.length} rows, generatedAt: ${ledger.generatedAt ?? "?"})
// 원장이 유일한 소스다 — 목록 수정은 ledger 갱신 후 재생성으로만.
import Foundation

struct CatalogEntry: Identifiable, Hashable, Sendable {
    let id: String
    let category: String
    let tier: String
    let web: String
    let ios: String
    let docs: String
    let tests: String
    let bench: String
    let note: String

    /// ledger에 중복 id가 실존한다(AreaChart가 composites·finance 양쪽) — Identifiable은 복합키로.
    var uid: String { category + "/" + id }
}

enum ShowroomCatalog {
    static let ledgerGeneratedAt = ${esc(ledger.generatedAt ?? "?")}
    static let categories: [String] = [${CATEGORIES.map((c) => esc(c)).join(", ")}]
    static let categoryTitles: [String: String] = [
        "core": "Core", "layout": "Layout", "primitives": "Primitives",
        "hooks": "Behaviors", "composites": "Composites", "patterns": "Patterns",
        "finance": "Finance",
    ]

`;

for (const cat of CATEGORIES) {
  const list = byCategory.get(cat);
  swift += `    static let ${cat}: [CatalogEntry] = [\n${list.map(entry).join("\n")}\n    ]\n\n`;
}

swift += `    static let all: [CatalogEntry] = ${CATEGORIES.join(" + ")}

    static let byCategory: [String: [CatalogEntry]] = [
${CATEGORIES.map((c) => `        "${c}": ${c},`).join("\n")}
    ]
}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, swift);

const counts = CATEGORIES.map((c) => `${c} ${byCategory.get(c).length}`).join(" · ");
const iosDone = rows.filter((r) => r.ios === "done").length;
const iosNa = rows.filter((r) => r.ios === "n/a").length;
console.log(`ShowroomCatalog.swift 방출: ${rows.length}행 (${counts})`);
console.log(`iOS 진행: done ${iosDone} / n·a ${iosNa} / todo ${rows.length - iosDone - iosNa}`);
