/**
 * gen-exports — exports 맵·컴포넌트 목록 생성기 (03-web-arch §6.2, 검수 P1-1 해소).
 *
 * src/components/<dir>/element.ts 를 스캔해 3곳의 수기 동기화를 제거한다:
 *  1. package.json "exports" — 고정 엔트리 + ./<dir>·./<dir>/element (dir 알파벳순).
 *     JS 엔트리는 { types, default } 객체로 방출(types 조건 선행 — moduleResolution
 *     bundler/node16에서 d.ts 해석은 exports types 조건이 유일 경로, TS7016 방지.
 *     릴리스 드라이런 실측·release/CHECKLIST.md §0). 톱레벨 "types"도 함께 동기화.
 *  2. src/components.generated.ts — 전 컴포넌트 클래스 import/re-export + ALL_COMPONENTS
 *     (define.ts·index.ts가 이것만 소비 — 수기 배열 폐지)
 *  3. --check: 재생성 결과가 디스크와 다르면 exit 1 (drift 게이트 — `npm test` 선두에서 실행)
 *
 * 클래스 추출은 `export class JdXxx extends` 정적 파싱 — 폴더당 다클래스(page 3종,
 * show 2종) 허용, 파일 내 소스 순서 보존. 의존성 0 (node:fs/path만).
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const webDir = join(here, "..");
const componentsDir = join(webDir, "src/components");
const check = process.argv.includes("--check");

/* ── 스캔 ── */
const dirs = readdirSync(componentsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

const CLASS_RE = /^export class (Jd\w+) extends /gm;
const TAG_RE =
  /static\s+(?:override\s+)?(?:readonly\s+)?tag\s*=\s*(?:"([^"]+)"|'([^']+)'|([A-Za-z_$][\w$]*))/g;
const TAG_CONST_RE =
  /\bconst\s+([A-Za-z_$][\w$]*)\s*=\s*(?:"([^"]+)"|'([^']+)')/g;
/** 폴더 이름과 다른 태그(하위 요소) — 소비자는 폴더가 아니라 **태그**를 안다 */
const tagAliases = [];
const perDir = dirs.map((dir) => {
  const src = readFileSync(join(componentsDir, dir, "element.ts"), "utf8");
  const classes = [...src.matchAll(CLASS_RE)].map((m) => m[1]);
  if (classes.length === 0) {
    console.error(`✗ ${dir}/element.ts 에서 export class Jd* 를 찾지 못함`);
    process.exit(1);
  }
  const constants = new Map();
  for (const match of src.matchAll(TAG_CONST_RE)) {
    constants.set(match[1], match[2] ?? match[3]);
  }
  for (const m of src.matchAll(TAG_RE)) {
    const tagName = m[1] ?? m[2] ?? constants.get(m[3]);
    if (!tagName?.startsWith("jd-")) continue;
    const tag = tagName.slice(3);
    if (tag !== dir) tagAliases.push({ tag, dir });
  }
  return { dir, classes };
});
tagAliases.sort((a, b) => a.tag.localeCompare(b.tag));

/* ── (1) package.json exports ── */
const pkgPath = join(webDir, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
// dist/types는 dist와 구조 동형(tsc outDir dist/types, esbuild outbase src) —
// js 경로에서 d.ts 경로를 기계 유도한다. CSS 엔트리는 d.ts가 없으므로 문자열 유지.
const entry = (js) => ({
  types: js.replace("./dist/", "./dist/types/").replace(/\.js$/, ".d.ts"),
  default: js,
});
const exportsMap = {
  ".": entry("./dist/index.js"),
  "./define": entry("./dist/define.js"),
  "./content": entry("./dist/core/content.js"),
};
for (const { dir } of perDir) {
  exportsMap[`./${dir}`] = entry(`./dist/components/${dir}/index.js`);
  exportsMap[`./${dir}/element`] = entry(`./dist/components/${dir}/element.js`);
}
/* 하위 요소 별칭 — jd-card-header·jd-dock-item 처럼 폴더 이름과 태그가 다른 9종은
   `@junds/web/card-header` 로는 열리지 않았다(실측). 소비자가 아는 이름은 폴더가
   아니라 태그이므로 태그로도 같은 모듈을 연다 — 소유 폴더를 부르면 하위 요소까지
   함께 등록되므로 대상은 소유 폴더의 엔트리 그대로다. (DEC-044) */
for (const { tag, dir } of tagAliases) {
  if (exportsMap[`./${tag}`]) continue; // 같은 이름의 실제 폴더가 이기게 둔다
  exportsMap[`./${tag}`] = entry(`./dist/components/${dir}/index.js`);
  exportsMap[`./${tag}/element`] = entry(`./dist/components/${dir}/element.js`);
}
Object.assign(exportsMap, {
  "./behaviors": entry("./dist/behaviors/index.js"),
  "./behaviors/*": entry("./dist/behaviors/*.js"),
  "./junds.css": "./dist/junds.css",
  "./core.css": "./dist/core.css",
  "./css/*": "./dist/css/*",
  "./tokens.css": "./src/styles/tokens.css",
});
const nextPkg =
  JSON.stringify({ ...pkg, types: "./dist/types/index.d.ts", exports: exportsMap }, null, 2) + "\n";

/* ── (2) components.generated.ts ── */
const banner =
  "/* AUTO-GENERATED by scripts/gen-exports.mjs — DO NOT EDIT (03-web-arch §6.2) */\n";
const lines = [banner];
for (const { dir, classes } of perDir) {
  lines.push(`export { ${classes.join(", ")} } from "./components/${dir}/element.js";`);
}
lines.push("");
for (const { dir, classes } of perDir) {
  lines.push(`import { ${classes.join(", ")} } from "./components/${dir}/element.js";`);
}
lines.push("");
lines.push("/** 전 컴포넌트 클래스 — defineJunds() 전량 등록의 단일 소스 */");
lines.push("export const ALL_COMPONENTS = [");
for (const { classes } of perDir) for (const c of classes) lines.push(`  ${c},`);
lines.push("] as const;");
const nextGen = lines.join("\n") + "\n";
const genPath = join(webDir, "src/components.generated.ts");

/* ── 쓰기 or 검사 ── */
const read = (p) => {
  try {
    return readFileSync(p, "utf8");
  } catch {
    return null;
  }
};

if (check) {
  const drift = [];
  if (read(pkgPath) !== nextPkg) drift.push("package.json exports");
  if (read(genPath) !== nextGen) drift.push("src/components.generated.ts");
  if (drift.length) {
    console.error(`✗ gen-exports drift: ${drift.join(", ")} — node scripts/gen-exports.mjs 재실행 필요`);
    process.exit(1);
  }
  console.log(`✓ gen-exports drift 없음 (${perDir.length}폴더 · 클래스 ${perDir.reduce((a, b) => a + b.classes.length, 0)}종)`);
} else {
  writeFileSync(pkgPath, nextPkg);
  writeFileSync(genPath, nextGen);
  console.log(`✓ exports ${Object.keys(exportsMap).length}엔트리 · ALL_COMPONENTS ${perDir.reduce((a, b) => a + b.classes.length, 0)}종 생성`);
}
