import type { LabComponentDef } from "./types";

// Registry of components available in the Lab
export const labComponents: LabComponentDef[] = [
  // ──── Primitives ────
  {
    id: "Button",
    label: "Button",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "variant", type: "select", options: ["primary", "secondary", "danger", "ghost", "outline", "link"], defaultValue: "primary" },
      { name: "size", type: "select", options: ["xs", "sm", "md", "lg"], defaultValue: "md" },
      { name: "disabled", type: "boolean", defaultValue: false },
      { name: "fullWidth", type: "boolean", defaultValue: false },
      { name: "loading", type: "boolean", defaultValue: false },
    ],
    defaultChildren: "Button",
    acceptsChildren: true,
    minWidth: 60,
    minHeight: 32,
  },
  {
    id: "Input",
    label: "Input",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "placeholder", type: "text", defaultValue: "Enter text..." },
      { name: "inputSize", type: "select", options: ["sm", "md", "lg"], defaultValue: "md", label: "size" },
      { name: "disabled", type: "boolean", defaultValue: false },
      { name: "error", type: "boolean", defaultValue: false },
    ],
    minWidth: 160,
    minHeight: 36,
  },
  {
    id: "Textarea",
    label: "Textarea",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "placeholder", type: "text", defaultValue: "Enter text..." },
      { name: "rows", type: "number", defaultValue: 3 },
      { name: "disabled", type: "boolean", defaultValue: false },
      { name: "error", type: "boolean", defaultValue: false },
      { name: "autoResize", type: "boolean", defaultValue: false },
    ],
    minWidth: 200,
    minHeight: 80,
  },
  {
    id: "Badge",
    label: "Badge",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "variant", type: "select", options: ["default", "primary", "success", "warning", "danger", "info", "outline"], defaultValue: "default" },
      { name: "size", type: "select", options: ["sm", "md", "lg"], defaultValue: "md" },
      { name: "dot", type: "boolean", defaultValue: false },
    ],
    defaultChildren: "Badge",
    acceptsChildren: true,
    minWidth: 40,
    minHeight: 20,
  },
  {
    id: "Avatar",
    label: "Avatar",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "name", type: "text", defaultValue: "User", label: "name" },
      { name: "src", type: "text", defaultValue: undefined },
      { name: "size", type: "select", options: ["xs", "sm", "md", "lg", "xl"], defaultValue: "md" },
    ],
    minWidth: 36,
    minHeight: 36,
  },
  {
    id: "Spinner",
    label: "Spinner",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "size", type: "select", options: ["xs", "sm", "md", "lg"], defaultValue: "md" },
      { name: "color", type: "select", options: ["primary", "white", "muted"], defaultValue: "primary" },
    ],
    minWidth: 24,
    minHeight: 24,
  },
  {
    id: "Toggle",
    label: "Toggle",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "checked", type: "boolean", defaultValue: false },
      { name: "size", type: "select", options: ["sm", "md"], defaultValue: "md" },
      { name: "label", type: "text", defaultValue: "" },
      { name: "disabled", type: "boolean", defaultValue: false },
    ],
    minWidth: 40,
    minHeight: 22,
  },
  {
    id: "Checkbox",
    label: "Checkbox",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "checked", type: "boolean", defaultValue: false },
      { name: "label", type: "text", defaultValue: "Checkbox" },
      { name: "disabled", type: "boolean", defaultValue: false },
      { name: "size", type: "select", options: ["sm", "md"], defaultValue: "md" },
    ],
    minWidth: 80,
    minHeight: 20,
  },
  {
    id: "Switch",
    label: "Switch",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "checked", type: "boolean", defaultValue: false },
      { name: "size", type: "select", options: ["sm", "md", "lg"], defaultValue: "md" },
      { name: "label", type: "text", defaultValue: "" },
      { name: "disabled", type: "boolean", defaultValue: false },
    ],
    minWidth: 44,
    minHeight: 24,
  },
  {
    id: "StarRating",
    label: "StarRating",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "value", type: "number", defaultValue: 3 },
      { name: "max", type: "number", defaultValue: 5 },
      { name: "size", type: "select", options: ["sm", "md", "lg"], defaultValue: "md" },
      { name: "readonly", type: "boolean", defaultValue: true },
    ],
    minWidth: 100,
    minHeight: 24,
  },
  {
    id: "Tag",
    label: "Tag",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "color", type: "select", options: ["gray", "primary", "blue", "green", "red", "orange", "purple", "teal"], defaultValue: "gray" },
      { name: "closable", type: "boolean", defaultValue: false },
    ],
    defaultChildren: "Tag",
    acceptsChildren: true,
    minWidth: 40,
    minHeight: 22,
  },
  {
    id: "Divider",
    label: "Divider",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "orientation", type: "select", options: ["horizontal", "vertical"], defaultValue: "horizontal" },
      { name: "label", type: "text", defaultValue: "" },
    ],
    minWidth: 120,
    minHeight: 1,
  },
  {
    id: "Label",
    label: "Label",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "required", type: "boolean", defaultValue: false },
    ],
    defaultChildren: "Label",
    acceptsChildren: true,
    minWidth: 40,
    minHeight: 20,
  },
  {
    id: "IconButton",
    label: "IconButton",
    category: "Primitives",
    importPath: "@/ds",
    props: [
      { name: "variant", type: "select", options: ["ghost", "outline", "filled"], defaultValue: "ghost" },
      { name: "size", type: "select", options: ["xs", "sm", "md", "lg"], defaultValue: "md" },
      { name: "disabled", type: "boolean", defaultValue: false },
      { name: "label", type: "text", defaultValue: "icon button", label: "aria-label" },
    ],
    minWidth: 32,
    minHeight: 32,
  },

  // ──── Composites ────
  {
    id: "Card",
    label: "Card",
    category: "Composites",
    importPath: "@/ds",
    props: [
      { name: "hoverable", type: "boolean", defaultValue: false },
      { name: "noPadding", type: "boolean", defaultValue: false },
    ],
    defaultChildren: "Card content",
    acceptsChildren: true,
    minWidth: 200,
    minHeight: 100,
  },
  {
    id: "Alert",
    label: "Alert",
    category: "Composites",
    importPath: "@/ds",
    props: [
      { name: "variant", type: "select", options: ["info", "success", "warning", "danger"], defaultValue: "info" },
      { name: "title", type: "text", defaultValue: "Alert Title" },
    ],
    defaultChildren: "Alert message",
    acceptsChildren: true,
    minWidth: 240,
    minHeight: 48,
  },
  {
    id: "Skeleton",
    label: "Skeleton",
    category: "Composites",
    importPath: "@/ds",
    props: [
      { name: "variant", type: "select", options: ["text", "circle", "rect"], defaultValue: "rect" },
      { name: "width", type: "text", defaultValue: "100%" },
      { name: "height", type: "text", defaultValue: "100" },
      { name: "lines", type: "number", defaultValue: 1 },
    ],
    minWidth: 60,
    minHeight: 20,
  },
  {
    id: "ProgressBar",
    label: "ProgressBar",
    category: "Composites",
    importPath: "@/ds",
    props: [
      { name: "value", type: "number", defaultValue: 50 },
      { name: "max", type: "number", defaultValue: 100 },
      { name: "variant", type: "select", options: ["default", "success", "warning", "danger"], defaultValue: "default" },
      { name: "size", type: "select", options: ["sm", "md", "lg"], defaultValue: "md" },
      { name: "showLabel", type: "boolean", defaultValue: false },
    ],
    minWidth: 120,
    minHeight: 8,
  },
  {
    id: "SegmentedControl",
    label: "SegmentedControl",
    category: "Composites",
    importPath: "@/ds",
    props: [
      { name: "size", type: "select", options: ["sm", "md", "lg"], defaultValue: "md" },
      { name: "fullWidth", type: "boolean", defaultValue: false },
    ],
    minWidth: 200,
    minHeight: 36,
  },
  {
    id: "Tabs",
    label: "Tabs",
    category: "Composites",
    importPath: "@/ds",
    props: [
      { name: "variant", type: "select", options: ["underline", "pills", "segment"], defaultValue: "underline" },
      { name: "size", type: "select", options: ["sm", "md"], defaultValue: "md" },
    ],
    minWidth: 200,
    minHeight: 36,
  },
];

// Build lookup map
export const labComponentMap = new Map<string, LabComponentDef>(
  labComponents.map((c) => [c.id, c]),
);
